### ISSUE TITLE
Autoshell hanging on start

### ISSUE THREAD

**Issue by PackeTsar** [PackeTsar/autoshell#3]
Hitting CTRL+C and not getting a response for several seconds. Then it does this:

```
^C^C^C^C^C^C^C^CTraceback (most recent call last):
  File "/usr/bin/autoshell", line 6, in <module>
    from autoshell.__main__ import start
  File "/usr/lib/python3.6/site-packages/autoshell/__init__.py", line 4, in <module>
    from . import connectors
  File "/usr/lib/python3.6/site-packages/autoshell/connectors/__init__.py", line 1, in <module>
    from . import cli
  File "/usr/lib/python3.6/site-packages/autoshell/connectors/cli.py", line 14, in <module>
    import netmiko
  File "/usr/lib/python3.6/site-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/usr/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/usr/lib/python3.6/site-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/usr/lib/python3.6/site-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/usr/lib/python3.6/site-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 22, in <module>
    import paramiko
  File "/usr/lib/python3.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 90, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/lib/python3.6/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/usr/lib64/python3.6/site-packages/nacl/signing.py", line 17, in <module>
    import nacl.bindings
  File "/usr/lib64/python3.6/site-packages/nacl/bindings/__init__.py", line 377, in <module>
    sodium_init()
  File "/usr/lib64/python3.6/site-packages/nacl/bindings/sodium_core.py", line 32, in sodium_init
    ffi.init_once(_sodium_init, "libsodium")
  File "/usr/lib64/python3.6/site-packages/nacl/bindings/sodium_core.py", line 22, in _sodium_init
    ensure(lib.sodium_init() != -1,
```

**Comment by PackeTsar** [comment]
This is a generic issue with Netmiko hanging on import. If you have this issue:

Take a look at https://github.com/paramiko/paramiko/issues/1368

The Short Story Is:
- There is a paramiko (or possibly PyNaCl?) issue with limited entropy in `/dev/random`
- You can test this with `cat /proc/sys/kernel/random/entropy_avail` and see the current amount of random bytes
- Installing haveged (`apt-get install haveged`) should help this issue, test again after install to see better results
  - Installing this package should resolve the hanged import issues from my experience

**Comment by PackeTsar** [comment]
This is on a newly created AWS instance:

```
# cat /proc/version
Linux version 4.15.0-1021-aws (buildd@lcy01-amd64-001) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #21-Ubuntu SMP Tue Aug 28 10:23:07 UTC 2018
#
```
