### ISSUE TITLE
Traceback Error/Timeout with some commands

### ISSUE THREAD

**Issue by gianmaxfactor** [PackeTsar/autoshell#4]
Some time ago I was able to run the following

```
autoshell 57.236.4.252@cisco_asa -c myusername:mypassword -m cmd -C "sh conn long address 57.236.4.55 address 192.168.175.141"
```

but I can't anymore. It always returns the following:

```
2021-04-21 21:54:54,122 [Thread-13   ] [ERROR]  common.autoqueue.autothread._supervisor: Exception raised in Thread-13:
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "c:\program files (x86)\python38-32\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\netmiko\base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "c:\program files (x86)\python38-32\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

_Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\autoshell\common\autoqueue.py", line 173, in _supervisor
    self._worker_func(self, item, *self._worker_args)
  File "c:\program files (x86)\python38-32\lib\site-packages\autoshell\modules\cmd.py", line 316, in cmd
    output += connection.send_command(command)
  File "c:\program files (x86)\python38-32\lib\site-packages\netmiko\cisco\cisco_asa_ssh.py", line 81, in send_command
    output = super().send_command(*args, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\netmiko\utilities.py", line 430, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\netmiko\base_connection.py", line 1490, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "c:\program files (x86)\python38-32\lib\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\netmiko\base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available._
```

I can anyway run the following succesfully (almost the same, just shortened):

```
autoshell 57.236.4.252@cisco_asa -c myusername:mypassword -m cmd -C "sh conn long address 57.236.4.55"
```

but it does NOT seem to be just a matter of command string length...

**Comment by PackeTsar** [comment]
Could it be a paging issue? If you SSH to the ASA manually and run that command, do you have to hit any keys on the keyboard (spacebar to page down, etc) in order to reach the bottom and get the regular prompt again?

**Comment by gianmaxfactor** [comment]
No keys to hit to reach the bottom, and even if so, I should at least get the initial output.

I have just run successfully:

`autoshell 57.236.4.252@cisco_asa -c myuser:mypwd -m cmd -C "sh conn long addre 57.236.4.55 sta up deta all pro tcp"`

but it breaks up if I run the almost identical:

`autoshell 57.236.4.252@cisco_asa -c myuser:mypwd -m cmd -C "sh conn long addre 57.236.4.55 sta up deta all pro*t* tcp"`

That's really driving me crazy.
